// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetJobs() {
  return window['go']['main']['ImageProcessor']['GetJobs']();
}

export function PauseJob(arg1) {
  return window['go']['main']['ImageProcessor']['PauseJob'](arg1);
}

export function ProcessFolder(arg1) {
  return window['go']['main']['ImageProcessor']['ProcessFolder'](arg1);
}

export function ResolveFolder(arg1) {
  return window['go']['main']['ImageProcessor']['ResolveFolder'](arg1);
}

export function ResumeJob(arg1) {
  return window['go']['main']['ImageProcessor']['ResumeJob'](arg1);
}

export function SelectFolder() {
  return window['go']['main']['ImageProcessor']['SelectFolder']();
}

export function StopJob(arg1) {
  return window['go']['main']['ImageProcessor']['StopJob'](arg1);
}
