// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetJobs():Promise<Array<main.JobDisplay>>;

export function PauseJob(arg1:string):Promise<void>;

export function ProcessFolder(arg1:string):Promise<string>;

export function ResolveFolder(arg1:string):Promise<string>;

export function ResumeJob(arg1:string):Promise<void>;

export function SelectFolder():Promise<string>;

export function StopJob(arg1:string):Promise<void>;
